### ISSUE TITLE
Enhancement: 建议添加课程时间

### ISSUE THREAD

**Issue by caodong0225** [Time-consumer/Course-Spider-for-USST#1]
![屏幕截图 2024-05-23 230246](https://github.com/InkyZigi/Course-Spider-for-USST/assets/84652389/4f21ac21-040f-47be-98a8-649b5bb21462)
如图所示，如果同一个老师在不同时间段上同一个课程，那么这个脚本默认是抢选第一个符合要求的课程。
但是我希望能够通过上课时间，精准的指定上这个老师周几的这门课程

**Comment by InkyZigi** [comment]
已收到建议
